version: '3'

services:
  webapplication1:
    image: pomelomysqlerrorweb
    build:
      context: .
      dockerfile: PomeloMySqlError.Web/Dockerfile
    depends_on:
    - mysqlserver
    links:
    - mysqlserver
  mysqlserver:
    image: mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=my-secret-pw
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10